### ISSUE TITLE
AttributeError: module 'hermit' has no attribute 'ui'

### ISSUE THREAD

**Issue by kirillkovalenko** [unchained-capital/hermit#17]
Hermit won't start

```
Traceback (most recent call last):
  File "/home/kirill/.local/bin/hermit", line 4, in <module>
    from hermit.ui import main
  File "/home/kirill/.local/lib/python3.6/site-packages/hermit/ui/__init__.py", line 1, in <module>
    from .main import main
  File "/home/kirill/.local/lib/python3.6/site-packages/hermit/ui/main.py", line 5, in <module>
    from .wallet import *
  File "/home/kirill/.local/lib/python3.6/site-packages/hermit/ui/wallet.py", line 8, in <module>
    from .repl import repl
  File "/home/kirill/.local/lib/python3.6/site-packages/hermit/ui/repl.py", line 12, in <module>
    from .toolbar import *
  File "/home/kirill/.local/lib/python3.6/site-packages/hermit/ui/toolbar.py", line 4, in <module>
    import hermit.ui.state as state
AttributeError: module 'hermit' has no attribute 'ui'
```

- Operation system & version: [Windows 1903, WSL]
- Python & pip versions: [pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)]
- Terminal emulator: [bash.exe]

**Comment by Stadicus** [comment]
I run into the same issue as well on a new Ubuntu 18.04 LTS, when installing the pip package `hermit`:

```sh
# system dependencies
$ sudo apt install python3 python3-pip python3-venv libzbar0
$ python3 -m pip install --upgrade pip

# set python3 as default, just to be sure as bin/hermit uses "#!/usr/bin/env python"
$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# install
$ python -m venv ~/hermit-env/
(hermit-env) $ cd ~/hermit-env/
(hermit-env) $ python3 -m pip install hermit

# run
(hermit-env) $:~/hermit-env$ hermit
Traceback (most recent call last):
  File "/home/stadicus/hermit-env/bin/hermit", line 4, in <module>
    from hermit.ui import main
  File "/home/stadicus/hermit-env/lib/python3.6/site-packages/hermit/ui/__init__.py", line 1, in <module>
    from .main import main
  File "/home/stadicus/hermit-env/lib/python3.6/site-packages/hermit/ui/main.py", line 5, in <module>
    from .wallet import *
  File "/home/stadicus/hermit-env/lib/python3.6/site-packages/hermit/ui/wallet.py", line 8, in <module>
    from .repl import repl
  File "/home/stadicus/hermit-env/lib/python3.6/site-packages/hermit/ui/repl.py", line 12, in <module>
    from .toolbar import *
  File "/home/stadicus/hermit-env/lib/python3.6/site-packages/hermit/ui/toolbar.py", line 4, in <module>
    import hermit.ui.state as state
AttributeError: module 'hermit' has no attribute 'ui'
```
_(can provide full logs if helpful)_

Although there is not error message clearly stating this, it seems that Python 3.7 is required (see [setup.py](https://github.com/unchained-capital/hermit/blob/master/setup.py)). I use the default versions of this Ubuntu release: Python 3.6.9 and pip 20.0.2. An update to Python 3.7 is tricky and not really supported.
