### ISSUE TITLE
Fresh build on OSX doesn't work

### ISSUE THREAD

**Issue by mflaxman** [unchained-capital/hermit#6]
**Describe the bug**
```
mflaxman@Michaels-MacBook-Pro:~/workspace$ git clone https://github.com/unchained-capital/hermit
Cloning into 'hermit'...
remote: Enumerating objects: 388, done.
remote: Counting objects: 100% (388/388), done.
remote: Compressing objects: 100% (291/291), done.
remote: Total 388 (delta 155), reused 315 (delta 90), pack-reused 0
Receiving objects: 100% (388/388), 386.73 KiB | 2.97 MiB/s, done.
Resolving deltas: 100% (155/155), done.

mflaxman@Michaels-MacBook-Pro:~/workspace$ cd hermit

mflaxman@Michaels-MacBook-Pro:~/workspace/hermit$ make
brew ls --versions zbar || brew install zbar
zbar 0.10_9
/usr/local/bin/python3 -m venv --prompt='hermit' .virtualenv
.virtualenv/bin/pip install wheel
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.33.6
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
.virtualenv/bin/pip install -r requirements.frozen.txt
Collecting alabaster==0.7.12 (from -r requirements.frozen.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting asn1crypto==0.24.0 (from -r requirements.frozen.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting atomicwrites==1.3.0 (from -r requirements.frozen.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting attrs==19.1.0 (from -r requirements.frozen.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting Babel==2.7.0 (from -r requirements.frozen.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/2c/60/f2af68eb046c5de5b1fe6dd4743bf42c074f7141fe7b2737d3061533b093/Babel-2.7.0-py2.py3-none-any.whl
Collecting bleach==3.1.0 (from -r requirements.frozen.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl
Collecting bson==0.5.8 (from -r requirements.frozen.txt (line 7))
Collecting certifi==2019.6.16 (from -r requirements.frozen.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting cffi==1.12.3 (from -r requirements.frozen.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/f0/48/5aa4ea664eba26dd5142558d04762f5065c02220b4665b3f7eecb9bb614e/cffi-1.12.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting chardet==3.0.4 (from -r requirements.frozen.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting Click==7.0 (from -r requirements.frozen.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting colorama==0.4.1 (from -r requirements.frozen.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting coverage==4.5.4 (from -r requirements.frozen.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/93/07/8302163cdbe2008441aa69f2119750110fde15ffd8a56a687311b143365a/coverage-4.5.4-cp37-cp37m-macosx_10_13_x86_64.whl
Collecting cryptography==2.7 (from -r requirements.frozen.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/63/4e/57b7a6bd98906872fcd2531e74b532de2abe17d675a5cf171931fcb4a9e8/cryptography-2.7-cp34-abi3-macosx_10_6_intel.whl
Collecting docutils==0.15.2 (from -r requirements.frozen.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting ecdsa==0.13 (from -r requirements.frozen.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/63/f4/73669d51825516ce8c43b816c0a6b64cd6eb71d08b99820c00792cb42222/ecdsa-0.13-py2.py3-none-any.whl
Collecting entrypoints==0.3 (from -r requirements.frozen.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting flake8==3.7.7 (from -r requirements.frozen.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/e9/76/b915bd28976068a9843bf836b789794aa4a8eb13338b23581005cd9177c0/flake8-3.7.7-py2.py3-none-any.whl
Collecting idna==2.8 (from -r requirements.frozen.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting imagesize==1.1.0 (from -r requirements.frozen.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Collecting importlib-metadata==0.19 (from -r requirements.frozen.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/ad/aa/25fcbded2ab4ed4ff3071d1e000cd4f8f9c65653d2d7157dd105a8e81d42/importlib_metadata-0.19-py2.py3-none-any.whl
Collecting imutils==0.5.1 (from -r requirements.frozen.txt (line 22))
Collecting Jinja2==2.10.1 (from -r requirements.frozen.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting MarkupSafe==1.1.1 (from -r requirements.frozen.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/ce/c6/f000f1af136ef74e4a95e33785921c73595c5390403f102e9b231b065b7a/MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl
Collecting mccabe==0.6.1 (from -r requirements.frozen.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting mnemonic==0.18 (from -r requirements.frozen.txt (line 26))
Collecting more-itertools==7.2.0 (from -r requirements.frozen.txt (line 27))
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Collecting mypy==0.701 (from -r requirements.frozen.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/aa/f3/74577ff2b4f29c4b8112b7dc22746ce41c88c36a3e1829641a1b1ec09e3b/mypy-0.701-cp37-cp37m-macosx_10_6_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting mypy-extensions==0.4.1 (from -r requirements.frozen.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/4d/72/8d54e2b296631b9b14961d583e56e90d9d7fba8a240d5ce7f1113cc5e887/mypy_extensions-0.4.1-py2.py3-none-any.whl
Collecting numpy==1.17.0 (from -r requirements.frozen.txt (line 30))
  Using cached https://files.pythonhosted.org/packages/c1/4b/78119133136c20e5ad2e01bf72b0633241defd619939908223cd394a9c32/numpy-1.17.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting opencv-python==3.4.3.18 (from -r requirements.frozen.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/e2/96/e7a196456fa75c75a7759c98fa6ba5bdacebdd66fbf4fd31e10b80f9d32e/opencv_python-3.4.3.18-cp37-cp37m-macosx_10_6_x86_64.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting packaging==19.1 (from -r requirements.frozen.txt (line 32))
  Using cached https://files.pythonhosted.org/packages/ec/22/630ac83e8f8a9566c4f88038447ed9e16e6f10582767a01f31c769d9a71e/packaging-19.1-py2.py3-none-any.whl
Collecting pbkdf2==1.3 (from -r requirements.frozen.txt (line 33))
Collecting Pillow==6.1.0 (from -r requirements.frozen.txt (line 34))
  Using cached https://files.pythonhosted.org/packages/8f/f3/c6d351d7e582e4f2ef4343c9be1f0472cb249fb69695e68631e337f4b6e9/Pillow-6.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pkginfo==1.5.0.1 (from -r requirements.frozen.txt (line 35))
  Using cached https://files.pythonhosted.org/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
Collecting pluggy==0.12.0 (from -r requirements.frozen.txt (line 36))
  Using cached https://files.pythonhosted.org/packages/06/ee/de89e0582276e3551df3110088bf20844de2b0e7df2748406876cc78e021/pluggy-0.12.0-py2.py3-none-any.whl
Collecting prompt-toolkit==2.0.7 (from -r requirements.frozen.txt (line 37))
  Using cached https://files.pythonhosted.org/packages/d1/e6/adb3be5576f5d27c6faa33f1e9fea8fe5dbd9351db12148de948507e352c/prompt_toolkit-2.0.7-py3-none-any.whl
Collecting py==1.8.0 (from -r requirements.frozen.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting pyAesCrypt==0.4.2 (from -r requirements.frozen.txt (line 39))
  Using cached https://files.pythonhosted.org/packages/65/f4/eacfcc319fda64428cd985d6ccb2a7f130feeca3c2fcc1dd8822b3b7b414/pyAesCrypt-0.4.2-py3-none-any.whl
Collecting pycodestyle==2.5.0 (from -r requirements.frozen.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting pycparser==2.19 (from -r requirements.frozen.txt (line 41))
Collecting pyflakes==2.1.1 (from -r requirements.frozen.txt (line 42))
  Using cached https://files.pythonhosted.org/packages/84/f2/ed0ffb887f8138a8fe5a621b8c0bb9598bfb3989e029f6c6a85ee66628ee/pyflakes-2.1.1-py2.py3-none-any.whl
Collecting Pygments==2.4.2 (from -r requirements.frozen.txt (line 43))
  Using cached https://files.pythonhosted.org/packages/5c/73/1dfa428150e3ccb0fa3e68db406e5be48698f2a979ccbcec795f28f44048/Pygments-2.4.2-py2.py3-none-any.whl
Collecting pyparsing==2.4.2 (from -r requirements.frozen.txt (line 44))
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting pysha3==1.0.2 (from -r requirements.frozen.txt (line 45))
Collecting pytest==4.4.0 (from -r requirements.frozen.txt (line 46))
  Using cached https://files.pythonhosted.org/packages/7e/16/83b2a35c427b838df9836c9e7e4ae6dfbcbdea643db44652f693b1c57d70/pytest-4.4.0-py2.py3-none-any.whl
Collecting pytest-cov==2.6.1 (from -r requirements.frozen.txt (line 47))
  Using cached https://files.pythonhosted.org/packages/7d/b5/92f32674ab954f80499ac73347bfeb815545ea295439c12b0ef3ac8f0975/pytest_cov-2.6.1-py2.py3-none-any.whl
Collecting python-bitcoinlib==0.10.1 (from -r requirements.frozen.txt (line 48))
  Using cached https://files.pythonhosted.org/packages/30/03/fb7df95fe89baede202cf3fe65e65bea4bf863061b5e8f59b12dab538240/python_bitcoinlib-0.10.1-py2.py3-none-any.whl
Collecting python-dateutil==2.8.0 (from -r requirements.frozen.txt (line 49))
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting pytz==2019.2 (from -r requirements.frozen.txt (line 50))
  Using cached https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl
Collecting PyYAML==5.1.1 (from -r requirements.frozen.txt (line 51))
Collecting pyzbar==0.1.7 (from -r requirements.frozen.txt (line 52))
  Using cached https://files.pythonhosted.org/packages/bd/e7/dc9aa3ee5ddc71df6ea1698f7e9d12dcc874346ad3051524155e121006a6/pyzbar-0.1.7-py2.py3-none-any.whl
Collecting qrcode==6.0 (from -r requirements.frozen.txt (line 53))
  Using cached https://files.pythonhosted.org/packages/79/be/11999004f7e6e5db0fa410c2feacd67c07f472f4500fde0026101f31d0df/qrcode-6.0-py2.py3-none-any.whl
Collecting readme-renderer==24.0 (from -r requirements.frozen.txt (line 54))
  Using cached https://files.pythonhosted.org/packages/c3/7e/d1aae793900f36b097cbfcc5e70eef82b5b56423a6c52a36dce51fedd8f0/readme_renderer-24.0-py2.py3-none-any.whl
Collecting requests==2.22.0 (from -r requirements.frozen.txt (line 55))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting requests-toolbelt==0.9.1 (from -r requirements.frozen.txt (line 56))
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting shamir-mnemonic==0.1.0 (from -r requirements.frozen.txt (line 57))
  Using cached https://files.pythonhosted.org/packages/da/7b/be61fae6dc3685197e3de75d78bcab7b40caac3235a235b2f8170cfc1cd2/shamir_mnemonic-0.1.0-py3-none-any.whl
Collecting six==1.12.0 (from -r requirements.frozen.txt (line 58))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting snowballstemmer==1.9.0 (from -r requirements.frozen.txt (line 59))
Collecting Sphinx==1.8.5 (from -r requirements.frozen.txt (line 60))
  Using cached https://files.pythonhosted.org/packages/7d/66/a4af242b4348b729b9d46ce5db23943ce9bca7da9bbe2ece60dc27f26420/Sphinx-1.8.5-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport==1.1.2 (from -r requirements.frozen.txt (line 61))
  Using cached https://files.pythonhosted.org/packages/2a/59/d64bda9b7480a84a3569be4dde267c0f6675b255ba63b4c8e84469940457/sphinxcontrib_websupport-1.1.2-py2.py3-none-any.whl
Collecting tqdm==4.32.2 (from -r requirements.frozen.txt (line 62))
  Using cached https://files.pythonhosted.org/packages/9f/3d/7a6b68b631d2ab54975f3a4863f3c4e9b26445353264ef01f465dc9b0208/tqdm-4.32.2-py2.py3-none-any.whl
Collecting twine==1.13.0 (from -r requirements.frozen.txt (line 63))
  Using cached https://files.pythonhosted.org/packages/28/90/59eec88c0b2ac9e47fe135959007acb93a3cc9f7146366e11fecf718dd15/twine-1.13.0-py2.py3-none-any.whl
Collecting typed-ast==1.3.5 (from -r requirements.frozen.txt (line 64))
  Using cached https://files.pythonhosted.org/packages/a4/7b/3d18d46c64c7052c5ad9b4301562cc46383c20dcbe69409b75cfd7096451/typed_ast-1.3.5-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting urllib3==1.25.3 (from -r requirements.frozen.txt (line 65))
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting wcwidth==0.1.7 (from -r requirements.frozen.txt (line 66))
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting webencodings==0.5.1 (from -r requirements.frozen.txt (line 67))
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting zipp==0.5.2 (from -r requirements.frozen.txt (line 68))
  Using cached https://files.pythonhosted.org/packages/da/bd/1a5fdf15aa44231fd09f63ecf175b60f057ae37ec65b343bb009364923f3/zipp-0.5.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.virtualenv/lib/python3.7/site-packages (from pytest==4.4.0->-r requirements.frozen.txt (line 46)) (40.8.0)
Installing collected packages: alabaster, asn1crypto, atomicwrites, attrs, pytz, Babel, six, webencodings, bleach, python-dateutil, bson, certifi, pycparser, cffi, chardet, Click, colorama, coverage, cryptography, docutils, ecdsa, entrypoints, pyflakes, pycodestyle, mccabe, flake8, idna, imagesize, zipp, importlib-metadata, imutils, MarkupSafe, Jinja2, pbkdf2, mnemonic, more-itertools, mypy-extensions, typed-ast, mypy, numpy, opencv-python, pyparsing, packaging, Pillow, pkginfo, pluggy, wcwidth, prompt-toolkit, py, pyAesCrypt, Pygments, pysha3, pytest, pytest-cov, python-bitcoinlib, PyYAML, pyzbar, qrcode, readme-renderer, urllib3, requests, requests-toolbelt, shamir-mnemonic, snowballstemmer, sphinxcontrib-websupport, Sphinx, tqdm, twine
Successfully installed Babel-2.7.0 Click-7.0 Jinja2-2.10.1 MarkupSafe-1.1.1 Pillow-6.1.0 PyYAML-5.1.1 Pygments-2.4.2 Sphinx-1.8.5 alabaster-0.7.12 asn1crypto-0.24.0 atomicwrites-1.3.0 attrs-19.1.0 bleach-3.1.0 bson-0.5.8 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 colorama-0.4.1 coverage-4.5.4 cryptography-2.7 docutils-0.15.2 ecdsa-0.13 entrypoints-0.3 flake8-3.7.7 idna-2.8 imagesize-1.1.0 importlib-metadata-0.19 imutils-0.5.1 mccabe-0.6.1 mnemonic-0.18 more-itertools-7.2.0 mypy-0.701 mypy-extensions-0.4.1 numpy-1.17.0 opencv-python-3.4.3.18 packaging-19.1 pbkdf2-1.3 pkginfo-1.5.0.1 pluggy-0.12.0 prompt-toolkit-2.0.7 py-1.8.0 pyAesCrypt-0.4.2 pycodestyle-2.5.0 pycparser-2.19 pyflakes-2.1.1 pyparsing-2.4.2 pysha3-1.0.2 pytest-4.4.0 pytest-cov-2.6.1 python-bitcoinlib-0.10.1 python-dateutil-2.8.0 pytz-2019.2 pyzbar-0.1.7 qrcode-6.0 readme-renderer-24.0 requests-2.22.0 requests-toolbelt-0.9.1 shamir-mnemonic-0.1.0 six-1.12.0 snowballstemmer-1.9.0 sphinxcontrib-websupport-1.1.2 tqdm-4.32.2 twine-1.13.0 typed-ast-1.3.5 urllib3-1.25.3 wcwidth-0.1.7 webencodings-0.5.1 zipp-0.5.2
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

mflaxman@Michaels-MacBook-Pro:~/workspace/hermit$ source environment.sh 
basename: illegal option -- b
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
[virtualenv] Entering Python virtualenv at /Users/mflaxman/workspace/hermit/.virtualenv
[pythonpath] /Users/mflaxman/workspace/hermit already on PYTHONPATH (:/Users/mflaxman/workspace/hermit)
[path]       Adding /Users/mflaxman/workspace/hermit/bin to PATH (/Users/mflaxman/workspace/hermit/.virtualenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/mflaxman/gocode/bin)

(hermit) mflaxman@Michaels-MacBook-Pro:~/workspace/hermit$ hermit
Traceback (most recent call last):
  File "/Users/mflaxman/workspace/hermit/bin/hermit", line 4, in <module>
    from hermit.ui import main
  File "/Users/mflaxman/workspace/hermit/hermit/__init__.py", line 3, in <module>
    from .wallet       import *
  File "/Users/mflaxman/workspace/hermit/hermit/wallet.py", line 5, in <module>
    from pybitcointools import (bip32_ckd,
ModuleNotFoundError: No module named 'pybitcointools'
```

**What is your environment?**
- Operation system & version: [Mac OS 10.14.5]
- Python & pip versions: [Python 3.7.4, pip 19.0.3]
- Terminal emulator: [Terminal.app]

**Comment by dhruvbansal** [comment]
I believe this is due to `pybitcointools` being vendored in as a git submodule.  If you run `git submodule update --init` that should work.  I have updated the readme to use `git clone --recursive` and updated the `environment.sh` script to print a helpful error message if it sees no submodule.

Can you please give it another try and let us know if it works for you?  Thanks!
